### ISSUE TITLE
How to set the feature set in editor script

### ISSUE THREAD

**Issue by JCMazza** [LocalJoost/HandCollider#2]
Hi, I am able to easily set xr loaders and able to set the meta quest feature set as well as interaction profile in code but I can not figure out how to set the hololens options and the xr runtime field via editor script openxr api has some attributes for meta quest but can't seem to find anything for hololens

Any idea?

**Comment by LocalJoost** [comment]
@JCMazza I hope you don't take this wrong, but I have really no idea what you mean. XR loaders? What is it what you are trying to do?

**Comment by JCMazza** [comment]
Closing this
